# Generated by Django 6.0.4 on 2026-05-23 18:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title_az', models.CharField(blank=True, help_text='Haqqımızda səhifəsində böyük başlıq.', max_length=120, null=True, verbose_name='Əsas başlıq (AZ)')),
                ('main_title_en', models.CharField(blank=True, max_length=120, null=True, verbose_name='Əsas başlıq (EN)')),
                ('main_title_ru', models.CharField(blank=True, max_length=120, null=True, verbose_name='Əsas başlıq (RU)')),
                ('second_title_az', models.CharField(blank=True, max_length=80, null=True, verbose_name='Alt başlıq (AZ)')),
                ('second_title_en', models.CharField(blank=True, max_length=80, null=True, verbose_name='Alt başlıq (EN)')),
                ('second_title_ru', models.CharField(blank=True, max_length=80, null=True, verbose_name='Alt başlıq (RU)')),
                ('description_az', models.TextField(help_text='Şirkət haqqında əsas mətn — Haqqımızda səhifəsində və ana səhifədə qısa blokda.', validators=[django.core.validators.MaxLengthValidator(4000)], verbose_name='Mətn (AZ)')),
                ('description_en', models.TextField(validators=[django.core.validators.MaxLengthValidator(4000)], verbose_name='Mətn (EN)')),
                ('description_ru', models.TextField(validators=[django.core.validators.MaxLengthValidator(4000)], verbose_name='Mətn (RU)')),
                ('video', models.FileField(blank=True, help_text='Haqqımızda və ana səhifədə göstərilən yeganə video. Yalnız bir fayl yükləyin.', null=True, upload_to='videos/about/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('mp4', 'webm', 'mov', 'ogg', 'mkv'), message='Allowed formats: mp4, webm, mov, ogg, mkv.')], verbose_name='Əsas tanıtım videosu')),
                ('video_poster', models.ImageField(blank=True, help_text='Video oynatılmadan əvvəl görünən şəkil.', null=True, upload_to='images/about/video_posters/', verbose_name='Video örtüyü (poster)')),
            ],
            options={
                'verbose_name': 'Haqqımızda səhifəsi',
                'verbose_name_plural': 'Haqqımızda səhifəsi',
            },
        ),
        migrations.CreateModel(
            name='AppealContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Ad soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, default='', max_length=40, verbose_name='Mobil nömrə')),
                ('subject', models.CharField(max_length=250, verbose_name='Mövzu')),
                ('info', models.TextField(validators=[django.core.validators.MaxLengthValidator(500)], verbose_name='Mesaj')),
                ('is_read', models.BooleanField(default=False, help_text='Mesajı oxuduqdan sonra işarələyin.', verbose_name='Oxunub?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gələn mesaj (əlaqə forması)',
                'verbose_name_plural': 'Gələn mesajlar (əlaqə forması)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_az', models.CharField(max_length=255, verbose_name='Başlıq (AZ)')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Başlıq (EN)')),
                ('name_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Başlıq (RU)')),
                ('image', models.ImageField(upload_to='blog/', verbose_name='Şəkil')),
                ('description_az', models.TextField(validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='Məzmun (AZ)')),
                ('description_en', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='Məzmun (EN)')),
                ('description_ru', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='Məzmun (RU)')),
                ('date', models.DateField(verbose_name='Tarix')),
                ('on_main_page', models.BooleanField(default=False, help_text='Ana səhifədə ən çox 6 bloq yazısı göstərilir.', verbose_name='Ana səhifədə göstərilsin?')),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Avtomatik sayılır — dəyişdirməyin.', verbose_name='Baxış sayı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bloq yazısı',
                'verbose_name_plural': 'Bloq yazıları',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_az', models.CharField(blank=True, max_length=500, verbose_name='Ünvan (AZ)')),
                ('address_en', models.CharField(blank=True, max_length=500, verbose_name='Ünvan (EN)')),
                ('address_ru', models.CharField(blank=True, max_length=500, verbose_name='Ünvan (RU)')),
                ('map_embed_url', models.URLField(blank=True, max_length=1000, verbose_name='Google Xəritə embed URL')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Telefon')),
                ('whatsapp_number', models.CharField(blank=True, max_length=40, verbose_name='WhatsApp nömrəsi')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-poçt')),
                ('email_two', models.EmailField(blank=True, max_length=254, verbose_name='Əlavə e-poçt')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('youtube', models.URLField(blank=True, verbose_name='YouTube')),
                ('linkedn', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('tiktok', models.URLField(blank=True, verbose_name='TikTok')),
            ],
            options={
                'verbose_name': 'Əlaqə məlumatları',
                'verbose_name_plural': 'Əlaqə məlumatları',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_az', models.CharField(max_length=500, verbose_name='Sual (AZ)')),
                ('question_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Sual (EN)')),
                ('question_ru', models.CharField(blank=True, max_length=500, null=True, verbose_name='Sual (RU)')),
                ('answer_az', models.TextField(verbose_name='Cavab (AZ)')),
                ('answer_en', models.TextField(blank=True, null=True, verbose_name='Cavab (EN)')),
                ('answer_ru', models.TextField(blank=True, null=True, verbose_name='Cavab (RU)')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Kiçik rəqəm = siyahıda yuxarıda. Məs: 1, 2, 3...', verbose_name='Sıra nömrəsi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Saytda göstərilsin?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tez-tez verilən sual',
                'verbose_name_plural': 'Tez-tez verilən suallar',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Motto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_az', models.TextField(help_text='Ana səhifə karuseli və ya səhifə bannerində görünən qısa cümlə.', validators=[django.core.validators.MaxLengthValidator(220)], verbose_name='Deviz mətni (AZ)')),
                ('text_en', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(220)], verbose_name='Deviz mətni (EN)')),
                ('text_ru', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(220)], verbose_name='Deviz mətni (RU)')),
                ('show_on_home_hero', models.BooleanField(default=True, help_text='Ana səhifənin yuxarı böyük şəkil slayderində bu deviz görünür.', verbose_name='Ana səhifə karuselində göstər?')),
                ('is_about_page', models.BooleanField(default=False, help_text='Haqqımızda səhifəsinin yuxarı fon şəklinin üstündə.', verbose_name='Haqqımızda səhifəsinin banneri')),
                ('is_contact_page', models.BooleanField(default=False, verbose_name='Əlaqə səhifəsinin banneri')),
                ('is_service_page', models.BooleanField(default=False, verbose_name='Xidmətlər səhifəsinin banneri')),
                ('is_blog_page', models.BooleanField(default=False, verbose_name='Bloq səhifəsinin banneri')),
            ],
            options={
                'verbose_name': 'Deviz (slogan)',
                'verbose_name_plural': 'Devizlər (sloganlar)',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_az', models.CharField(blank=True, max_length=120, null=True, validators=[django.core.validators.MaxLengthValidator(120)], verbose_name='Tərəfdaş adı (AZ)')),
                ('name_en', models.CharField(blank=True, max_length=120, null=True, validators=[django.core.validators.MaxLengthValidator(120)], verbose_name='Tərəfdaş adı (EN)')),
                ('name_ru', models.CharField(blank=True, max_length=120, null=True, validators=[django.core.validators.MaxLengthValidator(120)], verbose_name='Tərəfdaş adı (RU)')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('linkedn', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('is_active', models.BooleanField(default=True, help_text='Söndürsəniz tərəfdaş karuseldə görünməz.', verbose_name='Saytda göstərilsin?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tərəfdaş',
                'verbose_name_plural': 'Tərəfdaşlar',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('name_az', models.CharField(max_length=250, verbose_name='Xidmət adı (AZ)')),
                ('name_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='Xidmət adı (EN)')),
                ('name_ru', models.CharField(blank=True, max_length=250, null=True, verbose_name='Xidmət adı (RU)')),
                ('description_az', models.TextField(validators=[django.core.validators.MaxLengthValidator(500)], verbose_name='Xidmət haqqında (AZ)')),
                ('description_en', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(500)], verbose_name='Xidmət haqqında (EN)')),
                ('description_ru', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(500)], verbose_name='Xidmət haqqında (RU)')),
                ('is_active', models.BooleanField(blank=True, default=True, help_text='Söndürsəniz xidmət saytda görünməz.', null=True, verbose_name='Saytda göstərilsin?')),
                ('on_main_page', models.BooleanField(blank=True, default=False, help_text='Hər kateqoriyada ana səhifədə ən çox 6 xidmət ola bilər.', null=True, verbose_name='Ana səhifədə göstərilsin?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Xidmət',
                'verbose_name_plural': 'Xidmətlər',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('name_az', models.CharField(max_length=250, verbose_name='Kateqoriya adı (AZ)')),
                ('name_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='Kateqoriya adı (EN)')),
                ('name_ru', models.CharField(blank=True, max_length=250, null=True, verbose_name='Kateqoriya adı (RU)')),
            ],
            options={
                'verbose_name': 'Xidmət kateqoriyası',
                'verbose_name_plural': 'Xidmət kateqoriyaları',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_one', models.PositiveIntegerField(help_text='Məsələn: 25. Ana səhifə və Haqqımızda səhifəsində sol tərəfdəki birinci rəqəm.', verbose_name='1-ci kart — böyük rəqəm')),
                ('value_two', models.PositiveIntegerField(help_text='Məsələn: 150. İkinci statistika kartındakı rəqəm.', verbose_name='2-ci kart — böyük rəqəm')),
                ('value_three', models.PositiveIntegerField(help_text='Məsələn: 500. Üçüncü statistika kartındakı rəqəm.', verbose_name='3-cü kart — böyük rəqəm')),
                ('value_four', models.PositiveIntegerField(help_text='Məsələn: 1000. Dördüncü statistika kartındakı rəqəm.', verbose_name='4-cü kart — böyük rəqəm')),
                ('caption_one_az', models.CharField(blank=True, help_text='Rəqəmin altında görünən qısa mətn. Məs: İllik təcrübə', max_length=255, verbose_name='1-ci kart — alt yazı (AZ)')),
                ('caption_one_en', models.CharField(blank=True, help_text='English version of the caption below the first number.', max_length=255, verbose_name='1-ci kart — alt yazı (EN)')),
                ('caption_one_ru', models.CharField(blank=True, help_text='Русская версия подписи под первым числом.', max_length=255, verbose_name='1-ci kart — alt yazı (RU)')),
                ('caption_two_az', models.CharField(blank=True, help_text='Məs: Xidmət növü', max_length=255, verbose_name='2-ci kart — alt yazı (AZ)')),
                ('caption_two_en', models.CharField(blank=True, max_length=255, verbose_name='2-ci kart — alt yazı (EN)')),
                ('caption_two_ru', models.CharField(blank=True, max_length=255, verbose_name='2-ci kart — alt yazı (RU)')),
                ('caption_three_az', models.CharField(blank=True, help_text='Məs: Müştəri sayı', max_length=255, verbose_name='3-cü kart — alt yazı (AZ)')),
                ('caption_three_en', models.CharField(blank=True, max_length=255, verbose_name='3-cü kart — alt yazı (EN)')),
                ('caption_three_ru', models.CharField(blank=True, max_length=255, verbose_name='3-cü kart — alt yazı (RU)')),
                ('caption_four_az', models.CharField(blank=True, help_text='Məs: Layihə sayı', max_length=255, verbose_name='4-cü kart — alt yazı (AZ)')),
                ('caption_four_en', models.CharField(blank=True, max_length=255, verbose_name='4-cü kart — alt yazı (EN)')),
                ('caption_four_ru', models.CharField(blank=True, max_length=255, verbose_name='4-cü kart — alt yazı (RU)')),
            ],
            options={
                'verbose_name': 'Statistika (saylar bloku)',
                'verbose_name_plural': 'Statistika (saylar bloku)',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_az', models.CharField(blank=True, max_length=120, null=True, verbose_name='Ad (AZ)')),
                ('name_en', models.CharField(blank=True, max_length=120, null=True, verbose_name='Ad (EN)')),
                ('name_ru', models.CharField(blank=True, max_length=120, null=True, verbose_name='Ad (RU)')),
                ('short_description_az', models.TextField(blank=True, null=True, verbose_name='Qısa məlumat (AZ)')),
                ('short_description_en', models.TextField(blank=True, null=True, verbose_name='Qısa məlumat (EN)')),
                ('short_description_ru', models.TextField(blank=True, null=True, verbose_name='Qısa məlumat (RU)')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Şəkil')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Video')),
                ('is_home_page_background_image', models.BooleanField(default=False, verbose_name='Ana səhifə fon şəkli')),
                ('is_about_page_background_image', models.BooleanField(default=False, verbose_name='Haqqımızda səhifəsi fon şəkli')),
                ('is_contact_page_background_image', models.BooleanField(default=False, verbose_name='Əlaqə səhifəsi fon şəkli')),
                ('is_service_page_background_image', models.BooleanField(default=False, verbose_name='Xidmətlər səhifəsi fon şəkli')),
                ('is_blog_page_background_image', models.BooleanField(default=False, verbose_name='Bloq səhifələri fon şəkli')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('about', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='services.about', verbose_name='Haqqımızda')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='services.partner', verbose_name='Tərəfdaş')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='services.service', verbose_name='Xidmət')),
            ],
            options={
                'verbose_name': 'Səhifə banner fon şəkli',
                'verbose_name_plural': 'Səhifə banner fon şəkilləri',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicecategory', verbose_name='Kateqoriya'),
        ),
    ]
