# Generated by Django 6.0.4 on 2026-05-23 19:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('name_az', models.CharField(max_length=250, verbose_name='Paket adı (AZ)')),
                ('name_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='Paket adı (EN)')),
                ('name_ru', models.CharField(blank=True, max_length=250, null=True, verbose_name='Paket adı (RU)')),
                ('description_az', models.TextField(validators=[django.core.validators.MaxLengthValidator(500)], verbose_name='Paket haqqında (AZ)')),
                ('description_en', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(500)], verbose_name='Paket haqqında (EN)')),
                ('description_ru', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(500)], verbose_name='Paket haqqında (RU)')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Boş buraxıla bilər — saytda «Qiymət soruş» göstərilir.', max_digits=10, null=True, verbose_name='Qiymət')),
                ('duration_az', models.CharField(blank=True, help_text='Məs: 5 gün / 4 gecə', max_length=120, null=True, verbose_name='Müddət (AZ)')),
                ('duration_en', models.CharField(blank=True, max_length=120, null=True, verbose_name='Müddət (EN)')),
                ('duration_ru', models.CharField(blank=True, max_length=120, null=True, verbose_name='Müddət (RU)')),
                ('is_active', models.BooleanField(default=True, help_text='Söndürsəniz paket saytda görünməz.', verbose_name='Saytda göstərilsin?')),
                ('on_main_page', models.BooleanField(default=False, help_text='Ana səhifədə ən çox 6 paket göstərilir.', verbose_name='Ana səhifədə göstərilsin?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Paket',
                'verbose_name_plural': 'Paketlər',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
        migrations.AddField(
            model_name='media',
            name='is_package_page_background_image',
            field=models.BooleanField(default=False, verbose_name='Paketlər səhifəsi fon şəkli'),
        ),
        migrations.AddField(
            model_name='motto',
            name='is_package_page',
            field=models.BooleanField(default=False, verbose_name='Paketlər səhifəsinin banneri'),
        ),
        migrations.AlterField(
            model_name='service',
            name='on_main_page',
            field=models.BooleanField(blank=True, default=False, help_text='Ana səhifədə ən çox 6 xidmət göstərilir.', null=True, verbose_name='Ana səhifədə göstərilsin?'),
        ),
        migrations.AddField(
            model_name='media',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='services.package', verbose_name='Paket'),
        ),
        migrations.DeleteModel(
            name='ServiceCategory',
        ),
    ]
