# Generated by Django 5.2.14 on 2026-05-23 19:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_package_remove_service_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ('-created_at',), 'verbose_name': 'Paket', 'verbose_name_plural': 'Paketlər'},
        ),
        migrations.RemoveField(
            model_name='package',
            name='duration_az',
        ),
        migrations.RemoveField(
            model_name='package',
            name='duration_en',
        ),
        migrations.RemoveField(
            model_name='package',
            name='duration_ru',
        ),
        migrations.RemoveField(
            model_name='package',
            name='on_main_page',
        ),
        migrations.AddField(
            model_name='package',
            name='end_date',
            field=models.DateField(blank=True, help_text='Bu tarix keçdikdən sonra paket avtomatik olaraq saytda görünməz olacaq. Boş buraxsanız, paket müddətsiz olacaq.', null=True, verbose_name='Paket bitiş tarixi'),
        ),
        migrations.AddField(
            model_name='package',
            name='service',
            field=models.ManyToManyField(help_text='Bu paketə daxil olan xidmətləri seçin. Saytda paketlər xidmətlərlə birlikdə göstəriləcək.', related_name='packages', to='services.service', verbose_name='Xidmətlər'),
        ),
        migrations.AlterField(
            model_name='package',
            name='description_az',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='Məzmun (AZ)'),
        ),
        migrations.AlterField(
            model_name='package',
            name='description_en',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='Məzmun (EN)'),
        ),
        migrations.AlterField(
            model_name='package',
            name='description_ru',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='Məzmun (RU)'),
        ),
        migrations.AlterField(
            model_name='package',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, help_text='Söndürsəniz paket saytda görünməz.', null=True, verbose_name='Saytda göstərilsin?'),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=100, verbose_name='Qiymət'),
            preserve_default=False,
        ),
    ]
