# Generated by Django 6.0.4 on 2026-05-23 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_package_options_remove_package_duration_az_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='is_package_page_background_image',
        ),
    ]
