from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_remove_media_name_and_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='icon_one',
            field=models.CharField(
                choices=[
                    ('fas fa-calendar-check', 'Təqvim / təcrübə'),
                    ('fas fa-route', 'Marşrut / tur'),
                    ('fas fa-users', 'Müştərilər / qrup'),
                    ('fas fa-globe-americas', 'Beynəlxalq / dünya'),
                    ('fas fa-plane', 'Uçuş / səyahət'),
                    ('fas fa-hotel', 'Otel / qonaqlama'),
                    ('fas fa-map-marked-alt', 'Xəritə / məkan'),
                    ('fas fa-handshake', 'Tərəfdaşlıq'),
                    ('fas fa-award', 'Mükafat / keyfiyyət'),
                    ('fas fa-star', 'Ulduz / reytinq'),
                    ('fas fa-heart', 'Məmnuniyyət'),
                    ('fas fa-camera', 'Foto / xatirə'),
                    ('fas fa-bus', 'Nəqliyyat'),
                    ('fas fa-ship', 'Gəmi / kruiz'),
                    ('fas fa-mountain', 'Təbiət / macəra'),
                    ('fas fa-umbrella-beach', 'Çimərlik / istirahət'),
                    ('fas fa-passport', 'Viza / sənəd'),
                    ('fas fa-headset', 'Dəstək / xidmət'),
                    ('fas fa-chart-line', 'Artım / statistika'),
                    ('fas fa-thumbs-up', 'Tövsiyə'),
                ],
                default='fas fa-calendar-check',
                max_length=64,
                verbose_name='1-ci kart — ikon',
                help_text='Kartda görünən Font Awesome ikonu.',
            ),
        ),
        migrations.AddField(
            model_name='statistic',
            name='icon_two',
            field=models.CharField(
                choices=[
                    ('fas fa-calendar-check', 'Təqvim / təcrübə'),
                    ('fas fa-route', 'Marşrut / tur'),
                    ('fas fa-users', 'Müştərilər / qrup'),
                    ('fas fa-globe-americas', 'Beynəlxalq / dünya'),
                    ('fas fa-plane', 'Uçuş / səyahət'),
                    ('fas fa-hotel', 'Otel / qonaqlama'),
                    ('fas fa-map-marked-alt', 'Xəritə / məkan'),
                    ('fas fa-handshake', 'Tərəfdaşlıq'),
                    ('fas fa-award', 'Mükafat / keyfiyyət'),
                    ('fas fa-star', 'Ulduz / reytinq'),
                    ('fas fa-heart', 'Məmnuniyyət'),
                    ('fas fa-camera', 'Foto / xatirə'),
                    ('fas fa-bus', 'Nəqliyyat'),
                    ('fas fa-ship', 'Gəmi / kruiz'),
                    ('fas fa-mountain', 'Təbiət / macəra'),
                    ('fas fa-umbrella-beach', 'Çimərlik / istirahət'),
                    ('fas fa-passport', 'Viza / sənəd'),
                    ('fas fa-headset', 'Dəstək / xidmət'),
                    ('fas fa-chart-line', 'Artım / statistika'),
                    ('fas fa-thumbs-up', 'Tövsiyə'),
                ],
                default='fas fa-route',
                max_length=64,
                verbose_name='2-ci kart — ikon',
            ),
        ),
        migrations.AddField(
            model_name='statistic',
            name='icon_three',
            field=models.CharField(
                choices=[
                    ('fas fa-calendar-check', 'Təqvim / təcrübə'),
                    ('fas fa-route', 'Marşrut / tur'),
                    ('fas fa-users', 'Müştərilər / qrup'),
                    ('fas fa-globe-americas', 'Beynəlxalq / dünya'),
                    ('fas fa-plane', 'Uçuş / səyahət'),
                    ('fas fa-hotel', 'Otel / qonaqlama'),
                    ('fas fa-map-marked-alt', 'Xəritə / məkan'),
                    ('fas fa-handshake', 'Tərəfdaşlıq'),
                    ('fas fa-award', 'Mükafat / keyfiyyət'),
                    ('fas fa-star', 'Ulduz / reytinq'),
                    ('fas fa-heart', 'Məmnuniyyət'),
                    ('fas fa-camera', 'Foto / xatirə'),
                    ('fas fa-bus', 'Nəqliyyat'),
                    ('fas fa-ship', 'Gəmi / kruiz'),
                    ('fas fa-mountain', 'Təbiət / macəra'),
                    ('fas fa-umbrella-beach', 'Çimərlik / istirahət'),
                    ('fas fa-passport', 'Viza / sənəd'),
                    ('fas fa-headset', 'Dəstək / xidmət'),
                    ('fas fa-chart-line', 'Artım / statistika'),
                    ('fas fa-thumbs-up', 'Tövsiyə'),
                ],
                default='fas fa-users',
                max_length=64,
                verbose_name='3-cü kart — ikon',
            ),
        ),
        migrations.AddField(
            model_name='statistic',
            name='icon_four',
            field=models.CharField(
                choices=[
                    ('fas fa-calendar-check', 'Təqvim / təcrübə'),
                    ('fas fa-route', 'Marşrut / tur'),
                    ('fas fa-users', 'Müştərilər / qrup'),
                    ('fas fa-globe-americas', 'Beynəlxalq / dünya'),
                    ('fas fa-plane', 'Uçuş / səyahət'),
                    ('fas fa-hotel', 'Otel / qonaqlama'),
                    ('fas fa-map-marked-alt', 'Xəritə / məkan'),
                    ('fas fa-handshake', 'Tərəfdaşlıq'),
                    ('fas fa-award', 'Mükafat / keyfiyyət'),
                    ('fas fa-star', 'Ulduz / reytinq'),
                    ('fas fa-heart', 'Məmnuniyyət'),
                    ('fas fa-camera', 'Foto / xatirə'),
                    ('fas fa-bus', 'Nəqliyyat'),
                    ('fas fa-ship', 'Gəmi / kruiz'),
                    ('fas fa-mountain', 'Təbiət / macəra'),
                    ('fas fa-umbrella-beach', 'Çimərlik / istirahət'),
                    ('fas fa-passport', 'Viza / sənəd'),
                    ('fas fa-headset', 'Dəstək / xidmət'),
                    ('fas fa-chart-line', 'Artım / statistika'),
                    ('fas fa-thumbs-up', 'Tövsiyə'),
                ],
                default='fas fa-globe-americas',
                max_length=64,
                verbose_name='4-cü kart — ikon',
            ),
        ),
    ]
