# Generated by Django 5.2.14 on 2026-05-24 18:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_remove_package_icon_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='description_az',
            field=models.TextField(help_text='Maksimum 600 simvol. Saytda kart daxilindəki scroll bölməsində göstərilir.', validators=[django.core.validators.MaxLengthValidator(600)], verbose_name='Məzmun (AZ)'),
        ),
        migrations.AlterField(
            model_name='package',
            name='description_en',
            field=models.TextField(blank=True, help_text='Maksimum 600 simvol.', null=True, validators=[django.core.validators.MaxLengthValidator(600)], verbose_name='Məzmun (EN)'),
        ),
        migrations.AlterField(
            model_name='package',
            name='description_ru',
            field=models.TextField(blank=True, help_text='Maksimum 600 simvol.', null=True, validators=[django.core.validators.MaxLengthValidator(600)], verbose_name='Məzmun (RU)'),
        ),
    ]
