# Generated by Django 5.2.14 on 2026-05-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email'),
        ),
    ]
