# Generated by Django 5.2.14 on 2026-05-25 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_alter_review_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-created_at',), 'verbose_name': 'Rəy', 'verbose_name_plural': 'Reyler'},
        ),
    ]
