# Generated by Django 5.2.14 on 2026-05-27 10:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0025_appealcontact_email_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Ad soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, default='', max_length=40, verbose_name='Mobil nömrə')),
                ('note', models.TextField(validators=[django.core.validators.MaxLengthValidator(200)], verbose_name='Mesaj')),
                ('adults_count', models.PositiveIntegerField(default=1, verbose_name='Böyük sayı')),
                ('children_count', models.PositiveIntegerField(default=0, verbose_name='Uşaq sayı')),
                ('is_read', models.BooleanField(default=False, help_text='Sifarişi oxuduqdan sonra işarətlə bilərsiz.', verbose_name='Oxunub?')),
                ('is_customer', models.BooleanField(default=False, help_text='Bu şəxsin artıq müştəri olub olmadığını işarələyin', verbose_name='Müştərimizdir?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='services.package', verbose_name='Paket')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='services.service', verbose_name='Xidmət')),
            ],
            options={
                'verbose_name': 'Gələn mesaj (əlaqə forması)',
                'verbose_name_plural': 'Gələn mesajlar (əlaqə forması)',
                'ordering': ['-created_at'],
            },
        ),
    ]
