# Generated by Django 5.2.14 on 2026-05-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0028_booking_m2m_services_packages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Sifarişi oxuduqdan sonra işarələyin.', verbose_name='Oxunub?'),
        ),
    ]
