# Generated by Django 5.2.14 on 2026-05-27 11:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0029_alter_booking_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='note',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(200)], verbose_name='Mesaj'),
        ),
    ]
