# Generated by Django 6.0.4 on 2026-05-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0030_alter_booking_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sifariş', 'verbose_name_plural': 'Sifarişlər'},
        ),
        migrations.AddField(
            model_name='booking',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Sifarişi silmək əvəzinə “Silinib?” kimi işarələyin.', verbose_name='Silinib?'),
        ),
    ]
