# Generated by GPT-5.2 on 2026-05-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0031_booking_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='is_footer_contact_cta_background_image',
            field=models.BooleanField(default=False, verbose_name='Footer “Əlaqə saxla” düyməsi fonu'),
        ),
    ]

