# Generated by Django 5.2.14 on 2026-05-27 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0033_media_home_contact_bg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name': 'Sehife banner fon sekli', 'verbose_name_plural': 'Sehife banner fon sekilleri'},
        ),
        migrations.AlterField(
            model_name='media',
            name='about',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='services.about', verbose_name='Haqqimizda'),
        ),
        migrations.AlterField(
            model_name='media',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaradilma tarixi'),
        ),
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Sekil'),
        ),
        migrations.AlterField(
            model_name='media',
            name='is_about_page_background_image',
            field=models.BooleanField(default=False, verbose_name='Haqqimizda sehifesi fon sekli'),
        ),
        migrations.AlterField(
            model_name='media',
            name='is_blog_page_background_image',
            field=models.BooleanField(default=False, verbose_name='Bloq sehifeleri fon sekli'),
        ),
        migrations.AlterField(
            model_name='media',
            name='is_contact_page_background_image',
            field=models.BooleanField(default=False, verbose_name='Elaqe sehifesi fon sekli'),
        ),
        migrations.AlterField(
            model_name='media',
            name='is_footer_contact_cta_background_image',
            field=models.BooleanField(default=False, verbose_name='Footer Elaqe saxla duymesi fonu'),
        ),
        migrations.AlterField(
            model_name='media',
            name='is_home_page_background_image',
            field=models.BooleanField(default=False, verbose_name='Ana sehife fon sekli'),
        ),
        migrations.AlterField(
            model_name='media',
            name='is_service_page_background_image',
            field=models.BooleanField(default=False, verbose_name='Xidmetler sehifesi fon sekli'),
        ),
        migrations.AlterField(
            model_name='media',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='services.partner', verbose_name='Terefdasl'),
        ),
        migrations.AlterField(
            model_name='media',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='services.service', verbose_name='Xidmet'),
        ),
    ]
