# Generated by Django 5.2.14 on 2026-05-28 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0036_media_contact_booking_bg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-created_at',), 'verbose_name': 'Rəy', 'verbose_name_plural': 'Rəylər'},
        ),
    ]
