from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0037_alter_review_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='icon_one',
            field=models.CharField(
                blank=True,
                choices=[
                    ('fas fa-calendar-check', 'Təqvim / təcrübə'),
                    ('fas fa-route', 'Marşrut / tur'),
                    ('fas fa-users', 'Müştərilər / qrup'),
                    ('fas fa-globe-americas', 'Beynəlxalq / dünya'),
                    ('fas fa-plane', 'Uçuş / səyahət'),
                    ('fas fa-hotel', 'Otel / qonaqlama'),
                    ('fas fa-map-marked-alt', 'Xəritə / məkan'),
                    ('fas fa-handshake', 'Tərəfdaşlıq'),
                    ('fas fa-award', 'Mükafat / keyfiyyət'),
                    ('fas fa-star', 'Ulduz / reytinq'),
                    ('fas fa-heart', 'Məmnuniyyət'),
                    ('fas fa-camera', 'Foto / xatirə'),
                    ('fas fa-bus', 'Nəqliyyat'),
                    ('fas fa-ship', 'Gəmi / kruiz'),
                    ('fas fa-mountain', 'Təbiət / macəra'),
                    ('fas fa-umbrella-beach', 'Çimərlik / istirahət'),
                    ('fas fa-passport', 'Visa / sənəd'),
                    ('fas fa-headset', 'Dəstək / xidmət'),
                    ('fas fa-chart-line', 'Artım / statistika'),
                    ('fas fa-thumbs-up', 'Tövsiyə'),
                ],
                help_text='Kartda görünən Font Awesome ikonu.',
                max_length=64,
                null=True,
                verbose_name='1-ci kart — ikon',
            ),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='icon_two',
            field=models.CharField(
                blank=True,
                choices=[
                    ('fas fa-calendar-check', 'Təqvim / təcrübə'),
                    ('fas fa-route', 'Marşrut / tur'),
                    ('fas fa-users', 'Müştərilər / qrup'),
                    ('fas fa-globe-americas', 'Beynəlxalq / dünya'),
                    ('fas fa-plane', 'Uçuş / səyahət'),
                    ('fas fa-hotel', 'Otel / qonaqlama'),
                    ('fas fa-map-marked-alt', 'Xəritə / məkan'),
                    ('fas fa-handshake', 'Tərəfdaşlıq'),
                    ('fas fa-award', 'Mükafat / keyfiyyət'),
                    ('fas fa-star', 'Ulduz / reytinq'),
                    ('fas fa-heart', 'Məmnuniyyət'),
                    ('fas fa-camera', 'Foto / xatirə'),
                    ('fas fa-bus', 'Nəqliyyat'),
                    ('fas fa-ship', 'Gəmi / kruiz'),
                    ('fas fa-mountain', 'Təbiət / macəra'),
                    ('fas fa-umbrella-beach', 'Çimərlik / istirahət'),
                    ('fas fa-passport', 'Visa / sənəd'),
                    ('fas fa-headset', 'Dəstək / xidmət'),
                    ('fas fa-chart-line', 'Artım / statistika'),
                    ('fas fa-thumbs-up', 'Tövsiyə'),
                ],
                max_length=64,
                null=True,
                verbose_name='2-ci kart — ikon',
            ),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='icon_three',
            field=models.CharField(
                blank=True,
                choices=[
                    ('fas fa-calendar-check', 'Təqvim / təcrübə'),
                    ('fas fa-route', 'Marşrut / tur'),
                    ('fas fa-users', 'Müştərilər / qrup'),
                    ('fas fa-globe-americas', 'Beynəlxalq / dünya'),
                    ('fas fa-plane', 'Uçuş / səyahət'),
                    ('fas fa-hotel', 'Otel / qonaqlama'),
                    ('fas fa-map-marked-alt', 'Xəritə / məkan'),
                    ('fas fa-handshake', 'Tərəfdaşlıq'),
                    ('fas fa-award', 'Mükafat / keyfiyyət'),
                    ('fas fa-star', 'Ulduz / reytinq'),
                    ('fas fa-heart', 'Məmnuniyyət'),
                    ('fas fa-camera', 'Foto / xatirə'),
                    ('fas fa-bus', 'Nəqliyyat'),
                    ('fas fa-ship', 'Gəmi / kruiz'),
                    ('fas fa-mountain', 'Təbiət / macəra'),
                    ('fas fa-umbrella-beach', 'Çimərlik / istirahət'),
                    ('fas fa-passport', 'Visa / sənəd'),
                    ('fas fa-headset', 'Dəstək / xidmət'),
                    ('fas fa-chart-line', 'Artım / statistika'),
                    ('fas fa-thumbs-up', 'Tövsiyə'),
                ],
                max_length=64,
                null=True,
                verbose_name='3-cü kart — ikon',
            ),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='icon_four',
            field=models.CharField(
                blank=True,
                choices=[
                    ('fas fa-calendar-check', 'Təqvim / təcrübə'),
                    ('fas fa-route', 'Marşrut / tur'),
                    ('fas fa-users', 'Müştərilər / qrup'),
                    ('fas fa-globe-americas', 'Beynəlxalq / dünya'),
                    ('fas fa-plane', 'Uçuş / səyahət'),
                    ('fas fa-hotel', 'Otel / qonaqlama'),
                    ('fas fa-map-marked-alt', 'Xəritə / məkan'),
                    ('fas fa-handshake', 'Tərəfdaşlıq'),
                    ('fas fa-award', 'Mükafat / keyfiyyət'),
                    ('fas fa-star', 'Ulduz / reytinq'),
                    ('fas fa-heart', 'Məmnuniyyət'),
                    ('fas fa-camera', 'Foto / xatirə'),
                    ('fas fa-bus', 'Nəqliyyat'),
                    ('fas fa-ship', 'Gəmi / kruiz'),
                    ('fas fa-mountain', 'Təbiət / macəra'),
                    ('fas fa-umbrella-beach', 'Çimərlik / istirahət'),
                    ('fas fa-passport', 'Visa / sənəd'),
                    ('fas fa-headset', 'Dəstək / xidmət'),
                    ('fas fa-chart-line', 'Artım / statistika'),
                    ('fas fa-thumbs-up', 'Tövsiyə'),
                ],
                max_length=64,
                null=True,
                verbose_name='4-cü kart — ikon',
            ),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='value_one',
            field=models.PositiveIntegerField(
                blank=True,
                help_text='Məsələn: 25. Ana səhifə və Haqqımızda səhifəsində sol tərəfdəki birinci rəqəm.',
                null=True,
                verbose_name='1-ci kart — böyük rəqəm',
            ),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='value_two',
            field=models.PositiveIntegerField(
                blank=True,
                help_text='Məsələn: 150. İkinci statistika kartındakı rəqəm.',
                null=True,
                verbose_name='2-ci kart — böyük rəqəm',
            ),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='value_three',
            field=models.PositiveIntegerField(
                blank=True,
                help_text='Məsələn: 500. Üçüncü statistika kartındakı rəqəm.',
                null=True,
                verbose_name='3-cü kart — böyük rəqəm',
            ),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='value_four',
            field=models.PositiveIntegerField(
                blank=True,
                help_text='Məsələn: 1000. Dördüncü statistika kartındakı rəqəm.',
                null=True,
                verbose_name='4-cü kart — böyük rəqəm',
            ),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='caption_one_az',
            field=models.CharField(
                blank=True,
                help_text='Rəqəmin altında görünən qısa mətn. Məs: İllik təcrübə',
                max_length=255,
                null=True,
                verbose_name='1-ci kart — alt yazı (AZ)',
            ),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='caption_one_en',
            field=models.CharField(
                blank=True,
                help_text='English version of the caption below the first number.',
                max_length=255,
                null=True,
                verbose_name='1-ci kart — alt yazı (EN)',
            ),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='caption_one_ru',
            field=models.CharField(
                blank=True,
                help_text='Русская версия подписи под первым числом.',
                max_length=255,
                null=True,
                verbose_name='1-ci kart — alt yazı (RU)',
            ),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='caption_two_az',
            field=models.CharField(
                blank=True,
                help_text='Məs: Xidmət növü',
                max_length=255,
                null=True,
                verbose_name='2-ci kart — alt yazı (AZ)',
            ),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='caption_two_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='2-ci kart — alt yazı (EN)'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='caption_two_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='2-ci kart — alt yazı (RU)'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='caption_three_az',
            field=models.CharField(
                blank=True,
                help_text='Məs: Müştəri sayı',
                max_length=255,
                null=True,
                verbose_name='3-cü kart — alt yazı (AZ)',
            ),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='caption_three_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='3-cü kart — alt yazı (EN)'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='caption_three_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='3-cü kart — alt yazı (RU)'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='caption_four_az',
            field=models.CharField(
                blank=True,
                help_text='Məs: Layihə sayı',
                max_length=255,
                null=True,
                verbose_name='4-cü kart — alt yazı (AZ)',
            ),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='caption_four_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='4-cü kart — alt yazı (EN)'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='caption_four_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='4-cü kart — alt yazı (RU)'),
        ),
    ]
