# Generated by Django 5.2.14 on 2026-05-31 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0040_booking_date_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_from',
            field=models.DateField(blank=True, help_text='Səyahətin gediş tarixi.', null=True, verbose_name='Gediş tarixi'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_to',
            field=models.DateField(blank=True, help_text='Səyahətin qayıdış tarixi.', null=True, verbose_name='Qayıdış tarixi'),
        ),
    ]
