# Generated by Django 5.2.14 on 2026-05-31 12:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0041_alter_booking_date_from_alter_booking_date_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='note',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(600)], verbose_name='Mesaj'),
        ),
    ]
