# Generated by Django 5.2.15 on 2026-06-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0046_revert_package_price_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='icon_type',
        ),
        migrations.RemoveField(
            model_name='package',
            name='icon_variant',
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Qiymət'),
        ),
    ]
