# Generated by Django 5.2.15 on 2026-06-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0054_statistic_value_charfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='show_date_to',
            field=models.BooleanField(default=True, help_text='İşarələnərsə sifariş formunda qayıdış tarixi sahəsi göstərilir.', verbose_name='Sifariş formunda qayıdış tarixi'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='value_four',
            field=models.CharField(blank=True, help_text='Məsələn: 1000 və ya 90+. Dördüncü statistika kartındakı rəqəm.', max_length=32, null=True, verbose_name='4-ci kart — böyük rəqəm'),
        ),
    ]
